### ISSUE TITLE
Snap does not start

### ISSUE THREAD

**Issue by Edicksonjga** [ChainSafe/WebZjs#118]
After adding, accepting, confirming, installing and following each of the steps to be able to open the snap, it does not open, it stays in Loading... and it shows me an alert that the wallet must be unlocked, and yes, it is unlocked and still does not open.

I have tried with Brave, Google Chrome and Firefox and I have not been able to get it to start.

**Step by step:**
- Create your MetaMask wallet (create and save the unlock key and save the seed phrase)
- Search for the snap in the store
- Tap Install and follow the steps:
   - Add to MetaMask
   - Accept the connection request by tapping on Connect
   - Confirm permissions
   - Confirm that you want to install the snap
   - Click on the hyperlinks that take you to webzjs.chainsafe.dev or click on Open.
   - Make sure MetaMask is unlocked.
   - Tap Connect MetaMask Snap.
   - Accept the connection request by tapping on Connect.

In this last step, the snap stays in **Loading Web Wallet...**

<img width="1913" height="1031" alt="Image" src="https://github.com/user-attachments/assets/320f5e0d-d7b2-429e-a7a2-81e9ad1d8152" />

Tomorrow I should talk about this new alternative for Zcash users, as moderator of the Zcash community, I would love to do it, but if I can't start the snap, I will have to cancel the activity.

**Any solution to the problem?**

**Comment by irubido** [comment]
Hi,
thank you for reporting this behaviour. 

Bug was fixed with snap version 0.2.6.
Please try to connecting again and let us know if there are any other issues.

**Comment by Edicksonjga** [comment]
> Bug was fixed with snap version 0.2.6.
> Please try to connecting again and let us know if there are any other issues.

I have the version mentioned and the bug is still there. I have uninstalled and reinstalled it, but there is no solution.

**Comment by irubido** [comment]
@Edicksonjga @emersonian 
Hi
Please try when you get the chance, I've added error report on the landing if connecting fails(for troubleshooting)
Bug probably come from snap install happening before wallet completely initialized, and stored faulty wallet locally.
If any case if you delete IDB, reinstall snap and try again there should not be any problems.

**Comment by irubido** [comment]
@emersonian 
Also works on Firefox now.
